name: janus_mobile
description: janusmobile written in Dart

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  html: ^0.15.0
  nonce: ^1.2.0
  crypto: ^3.0.0
  intl: ^0.17.0
  dio: ^4.0.0 #^3.0.10
  uuid: ^3.0.1
  logger: ^1.0.0
  sqflite:
  path:
  #source_span: ^1.8.1
  #test_api: ^0.4.0
  #args: ^2.1.0
  #async: ^2.6.1
  googleapis: ^4.0.0  #3.0.0

  flutter_local_notifications: ^8.0.0 #^6.0.0 #^5.0.0
  firebase_core: ^1.0.2
  firebase_messaging: ^10.0.0 #^9.0.1
  #flutter_voip_push_notification: ^0.0.3
  dart_notification_center: ^1.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Keychain is used for iOS
  # AES encryption is used for Android. AES secret key is encrypted with RSA and RSA key is stored in KeyStore
  flutter_secure_storage: ^4.0.0

  # A Flutter plugin for Google Sign In.
  google_sign_in: ^5.0.0

  # Supports login via an Apple ID, as well as retrieving credentials saved in the user's keychain.
  sign_in_with_apple: ^3.0.0

  # A Flutter plugin for using the native Facebook Login SDKs on Android and iOS.
  flutter_facebook_login: ^3.0.0
  flutter_twitter: ^1.1.3
  twitter_api: ^0.1.2

  # Auth Buttons is a flutter widget library, include buttons for authenticating with the most popular social networks like: Google, Facebook, Apple and too other.
  auth_buttons: ^1.0.0

  # WebRTC plugin for Flutter Mobile/Desktop/Web
  flutter_webrtc: ^0.6.3  #^0.5.8

  #flutterjanus: ^0.0.5
  #janus_client: ^0.0.4

  path_provider: ^2.0.1
  web_socket_channel: ^2.0.0
  stream_channel: ^2.0.0

  url_launcher: ^6.0.2
  uni_links: ^0.5.1 #^0.4.0

  permission_handler: ^8.0.0+2  #^7.0.0
  font_awesome_flutter: ^9.0.0
  flutter_qr_reader: ^1.0.3
  #email_validator: ^2.0.1
  flutter_email_sender: ^5.0.2
  callkeep: ^0.3.0  #^0.2.3+1
  flutter_svg: ^0.22.0 #0.21.0+1
  #flutter_chat: ^2.0.1
  chat_ui_kit: ^1.1.7

  random_string: ^2.1.0
  sdp_transform: ^0.3.0 #^0.2.0
  image_picker: ^0.8.1+3  #^0.7.4
  video_player: ^2.1.1
  webview_flutter: ^2.0.4
  #webview_cookie_manager: ^2.0.0
  flutter_filereader: ^3.0.0 #^2.2.0
  confirm_dialog: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/icon.png
    - images/favicon.png
    - images/full_image.png
    - images/calling_face.png
    - images/icons/call_end.svg
    - images/icons/call_answer.svg
    - images/icons/Icon Mic.svg
    - images/icons/Icon Volume.svg
    - images/icons/Icon Video.svg
    - images/icons/Icon Message.svg
    - images/icons/Icon User.svg
    - images/icons/Icon Voicemail.svg
    - images/avatars/local_user_avatar.png
    - images/avatars/woman0.jpg
    - images/avatars/woman1.jpg
    - images/avatars/woman2.jpg
    - images/avatars/man0.jpg
    - images/avatars/man1.jpg
    - images/avatars/man2.jpg
    - images/other/paris_e_tower.jpg
    - assets/database.db

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
